### ISSUE TITLE
Repeat DOI in abstract - Health Sciences Theme

### ISSUE THREAD

**Issue by Ppantaleo** [lepidus/doiInSummary#2]
Hi, I use the Health Sciences theme in a Journal. In the homepage it works fine, but in previous issues it repeats twice the DOI in the abstract.

![image](https://github.com/lepidus/doiInSummary/assets/74371185/1a8967ff-039c-49cc-ab96-33daa626e259)

**Comment by diegoabadan** [comment]
Our team will check and get back to you shortly.

**Comment by diegoabadan** [comment]
The Health Sciences Theme in recent versions also tries to [add the DOIs](https://github.com/pkp/healthSciences/blob/4ad1a6f4cebf2c0f812ffbe060f662ee36c5766a/templates/frontend/objects/article_summary.tpl#L68) in the summary. In this case, the simplest thing to do is to disable our plugin in this journal so that there is no duplication.

Note: DOI support in the Health Sciences Theme summary may not be as stable, see https://github.com/pkp/healthSciences/issues/231.

**Comment by Ppantaleo** [comment]
Thank you very much for your answer.
