### ISSUE TITLE
Journal title: International Health Trends and Perspectives

### ISSUE THREAD

**Issue by sfrederij** [lepidus/doiInSummary#3]
Hello,
The DOI for our journal is not appearing when we launched our most recent issue on April 1. Can you please fix.
https://journals.library.torontomu.ca/index.php/ihtp/issue/view/146
Thank-you.

**Comment by YvesLepidus** [comment]
Hello, @sfrederij :smiley: 
We couldn't find the plugin in the reference OJS. The link we tested was: https://journals.library.torontomu.ca/plugins/generic/doiInSummary/version.xml. 
This is the expected behavior when the plugin is present in OJS, even if disabled, as we can see in this other example: https://revistadaanpoll.emnuvens.com.br/plugins/generic/doiInSummary/version.xml.
Can you confirm with us that the plugin is installed correctly? You can find it under `Settings` > `Website` > `Plugins` > `Plugin Gallery`.

**Comment by sfrederij** [comment]
Hello,
I don't know if it is installed correctly, but this is the journal here
<https://journals.library.torontomu.ca/index.php/ihtp>. The DOIs do not
appear when the issue is launched.
Any assistance would be appreciated.
Thank-you.

**Comment by diegoabadan** [comment]
Hi @sfrederij,

You have opened an issue regarding our plugin that displays the DOI in the table of contents. It only displays the DOI in the table of contents when the DOI is present in OJS and the plugin is installed and active.

In your case, where the DOIs are not appearing in OJS (for example, on the article page), you can consult the [official PKP documentation](https://docs.pkp.sfu.ca/). For example: https://docs.pkp.sfu.ca/doi-plugin/en/when-are-dois-assigned

If the documentation doesn't clarify things, the PKP forum is usually the ideal place to get help: https://forum.pkp.sfu.ca/

As this is not related to the plugin, I'm closing this issue.
